const ErrorCodes = {
  //Token
  UNAUTHORIZED: 401,
  //USERS
  USER_ALREADY_EXISTS: 500,
  USER_NOT_FOUND: 404,
  INVALID_USER: 404,
  PHONE_ALREADY_EXISTS: 500,

  //ROLES
  ROLE_NOT_FOUND: 404,
  ROLE_ALREADY_EXISTS: 500,

  //PERMISSIONS
  PERMISSION_NOT_FOUND: 404,
  PERMISSION_ALREADY_EXISTS: 500,

  // ROLE PERMISSIONS
  ROLE_PERMISSIONS_NOT_FOUND: 404,
  PERMISSIONS_AGAINST_ROLE_ALREADY_EXISTS: 500,
};

const SuccessCodes = {
  USER_LOGIN_SUCCESSFULLY: 200,
  USER_REGISTERED_SUCCESSFULLY: 200,
  PASSWORD_CREATED_SUCCESSFULLY: 200,
};

module.exports = {
  ErrorCodes,
  SuccessCodes,
};
